language: csharp

solution: MarketPlaceBackend.sln

notifications:

  email:

    on_success: always

    on_failure: always

  slack: srboeingdotnet:UIU3Bl3s8QViLrC2yS7GV9NI

mono: none

dotnet: 2.1

script:
  - chmod +x ./deploy.sh
  - dotnet restore MarketPlaceBackend/MarketPlaceBackend.csproj
  - dotnet restore MarketPlaceBackend.Tests/MarketPlaceBackend.Tests.csproj
  - dotnet test MarketPlaceBackend.Tests

after_success:
  - /bin/bash ./deploy.sh