version: '3.4'

services:
  web:
    build: ./MarketPlaceBackend
    depends_on:
        - db
    labels:
     - "SERVICE_NAME=marketplace-service"
     - "SERVICE_TAG=marketplace-serviceTag"
    expose:
     - "2720"
    restart: always
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"