version: '3.4'

services:
  web:
    build: ./MarketPlaceBackend
      # context: .
      #   dockerfile: dockerfile

    ports:
        - "2720:80"
    depends_on:
        - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"