version: '3.4'

services:
  web:
    build: ./MarketPlaceBackend
    ports: 
      - "2720:80"
    depends_on:
        - db
    labels:
     - "SERVICE_80_NAME=marketplace-service"
     - "SERVICE_TAG=marketplace-serviceTag"
    restart: on-failure
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"